name: 'website-build-deploy'

run-name: 'website-build-deploy - ${{ github.ref }} #${{ github.run_number }}'

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'website-build-deploy'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: pnpm --version
