name: 'website-build-deploy'

run-name: 'website-build-deploy - ${{ github.ref }} #${{ github.run_number }}'

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'website-build-deploy'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 10
          cache: false

      - name: Check pnpm version
        run: pnpm --version

      - name: Check working directory
        run: pwd
