name: 'website-build-deploy'

run-name: 'website-build-deploy - #${{ github.run_number }} - ${{ github.sha }}'

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: 'website-build-deploy'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
